export const ROUTE_MAP = {
  home: "/",
  "trang chủ": "/",
  products: "/products",
  "sản phẩm": "/products",
  cart: "/cart",
  "giỏ hàng": "/cart",
  account: "/account",
  "tài khoản": "/account",
  login: "/login",
  "đăng nhập": "/login",
  register: "/register",
  "đăng ký": "/register",
  blog: "/blog",
  "tin tức": "/blog",
  contact: "/lien-he",
  "liên hệ": "/lien-he",
  about: "/about",
  "giới thiệu": "/about",
  addresses: "/account/addresses",
  "địa chỉ": "/account/addresses",
  orders: "/account/orders",
  "đơn hàng": "/account/orders",
  wishlist: "/account/wishlist",
  "danh sách ưa thích": "/account/wishlist",
  "yêu thích": "/account/wishlist",
  "red wine": "/products?category=Rượu Vang Đỏ",
  "rượu vang đỏ": "/products?category=Rượu Vang Đỏ",
  "white wine": "/products?category=Rượu Vang Trắng",
  "rượu vang trắng": "/products?category=Rượu Vang Trắng",
  champagne: "/products?category=Champagne",
  rosé: "/products?category=Rượu Vang Rosé",
  "rượu vang rosé": "/products?category=Rượu Vang Rosé",
  "sweet wine": "/products?category=Rượu Vang Ngọt",
  "rượu vang ngọt": "/products?category=Rượu Vang Ngọt",
};
